apiVersion : apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name}}  
spec:
  replicas: {{ .Values.deployment.replicas}} 
  selector:
    matchLabels:
      app: {{ .Values.name}} 
  template:
    metadata:
      labels:
        app: {{ .Values.name}}  
    spec:
      containers:
        - name: {{ .Values.name}} 
          image: {{ .Values.deployment.image}}
          imagePullPolicy: "Always"
          ports:
          - containerPort: 8080
          envFrom:
          - configMapRef:
             name: {{ .Values.configMap}}
          - secretRef:
             name: {{ .Values.secret}}
